{% set name = "dprint" %}
{% set version = "0.47.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8d0095f6f35f11621783ab40fab4a9394829b96c3d1de8e844d319096d25a76d

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - dprint --help

about:
  home: https://dprint.dev
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Pluggable and configurable code formatting platform written in Rust
  dev_url: https://github.com/dprint

extra:
  recipe-maintainers:
    - danielnachun
