{% set name = "dprint" %}
{% set version = "0.47.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: bea9f14c5576ee5aaefea14839ae1f89005b4681fbf539b31460837bfa2bf92d

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - dprint --help

about:
  home: https://dprint.dev
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Pluggable and configurable code formatting platform written in Rust
  dev_url: https://github.com/dprint

extra:
  recipe-maintainers:
    - danielnachun
