context:
  version: "0.51.0"

package:
  name: dprint
  version: ${{ version }}

source:
  url: https://github.com/dprint/dprint/archive/${{ version }}.tar.gz
  sha256: 4c6ef41ea15012948854a44d85d6e20d0514c53b77f53464a135ea664186919d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - dprint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Pluggable and configurable code formatting platform written in Rust
  homepage: https://dprint.dev
  repository: https://github.com/dprint

extra:
  recipe-maintainers:
    - danielnachun
