context:
  version: 0.47.6

package:
  name: dprint
  version: ${{ version }}

source:
  url: https://github.com/dprint/dprint/archive/${{ version }}.tar.gz
  sha256: 8d0095f6f35f11621783ab40fab4a9394829b96c3d1de8e844d319096d25a76d

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - dprint --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Pluggable and configurable code formatting platform written in Rust
  homepage: https://dprint.dev
  repository: https://github.com/dprint

extra:
  recipe-maintainers:
    - danielnachun
